### ISSUE TITLE
Final Grade Page

### ISSUE THREAD

**Issue by eldev314** [cse110-sp23-group7/cse110_rogue#24]
Design and code the page that serves as the ending of our game. This will likely have to be done in conjunction with the encounter page mechanics to set up a system to make the player's action influence their end grade prediction, which will be some letter grade displayed in the center of the page. 

Include some basic thematically appropriate visuals along with this and optionally, some statistics/message helping the player understand how their actions in the game influenced this prediction. For example, "You watched too much Netflix and did bad on the midterm, from you were already doomed. Thus, you got an F in the course."

**Comment by z3qi** [comment]
#49
