### ISSUE TITLE
Make the Final Private Video 

### ISSUE THREAD

**Issue by nishantbegani9** [cse110-sp23-group7/cse110_rogue#60]
Definition of Done: Make 15-minute video-introduction of all team members and the work they have done. Walk through the whole Github repo, cicd pipeline, and documentation. Also, have a conclusion. 

Introduction - All Team Members
Walkthrough - Raj 
Conclusion - Nishant

**Comment by rajsunku** [comment]
Added to finalvideo.md in admin/videos
